### ISSUE TITLE
Maybe find a better name than "trivial-cdr"

### ISSUE THREAD

**Issue by fstamour** [fstamour/trivial-cdr#2]

**Comment by Gleefre** [comment]
Could be called IF-CDR  / IF:CDR  -- as in "Ideas For Common lisp Document Repository".

**Comment by Gleefre** [comment]
Could be called (CL-)CAR to "revive" / "inherit" from non-born CAR project (that would also allow to take use of an already being logged IRC channel `#cl-car`)

(lonjil gave a permission, IIUC lonjil was the main author behind the idea of CAR, maybe it is not true? Dunno)

**Comment by fstamour** [comment]
I think that is someone wants to create a repo for a specific CDR, they should use the naming convention `cdr-<name>`

**Comment by fstamour** [comment]
But for this current project... I don't know

- cdr-moodboard

**Comment by fstamour** [comment]
Let's go with cl-car, that's what I named my original gist after all, _past me can't be wrong_.

Also, I like that ~ "car is before cdr"

**Comment by Gleefre** [comment]
Sounds good.
It would probably make sense to reuse the `#cl-car` IRC channel as well then.

**Comment by fstamour** [comment]
I renamed the project.
